[package]
name = "heyyy"
description = "Simple load tester"
version = "0.1.2"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
reqwest = "0.12.22"
